# Generated by Django 4.0.2 on 2022-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('data', models.DateTimeField(verbose_name='Дата добавления')),
            ],
        ),
    ]
