# Generated by Django 4.0.2 on 2022-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='id_crated_user',
            field=models.CharField(default=True, max_length=1000, verbose_name='ID создавшего пользователя'),
        ),
        migrations.AddField(
            model_name='userfiles',
            name='id_crated_user',
            field=models.CharField(default=True, max_length=1000, verbose_name='ID создавшего пользователя'),
        ),
    ]
