# Generated by Django 4.0.2 on 2022-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Логин и пароль',
                'verbose_name_plural': 'Логины и пароли',
            },
        ),
        migrations.AlterModelOptions(
            name='user_data',
            options={'verbose_name': 'Файл пользователя', 'verbose_name_plural': 'Файлы пользователей'},
        ),
    ]
