# Generated by Django 4.0.2 on 2022-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
