# Generated by Django 4.0.2 on 2022-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0002_links_id_crated_user_userfiles_id_crated_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.IntegerField()),
                ('children', models.JSONField(verbose_name='[]')),
            ],
        ),
    ]
