# Generated by Django 4.0.2 on 2022-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0002_links_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=20, verbose_name='username'),
        ),
    ]
