# Generated by Django 4.0.2 on 2022-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0003_users_repeat_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
