# Generated by Django 4.0.2 on 2022-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0003_userdirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdirs',
            name='id_crated_user',
            field=models.CharField(default=1, max_length=1000, verbose_name='ID создавшего пользователя'),
        ),
        migrations.AlterField(
            model_name='userdirs',
            name='children',
            field=models.JSONField(verbose_name='Потомки'),
        ),
    ]
