# Generated by Django 4.0.2 on 2022-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0003_userfiles_alter_links_options_alter_links_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
