# Generated by Django 4.0.2 on 2022-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0003_userfiles_alter_links_options_alter_links_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='id_crated_user',
            field=models.CharField(default=5, max_length=1000, verbose_name='ID создавшего пользователя'),
        ),
        migrations.AddField(
            model_name='userfiles',
            name='id_crated_user',
            field=models.CharField(default=5, max_length=1000, verbose_name='ID создавшего пользователя'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
