# Generated by Django 4.0.2 on 2022-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0004_userdirs_id_crated_user_alter_userdirs_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='dirs',
            field=models.JSONField(default=[0], verbose_name='ID директорий, где есть файл'),
        ),
        migrations.AddField(
            model_name='userfiles',
            name='dirs',
            field=models.JSONField(default=[0], verbose_name='ID директорий, где есть файл'),
        ),
    ]
