# Generated by Django 4.0.2 on 2022-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0005_links_dirs_userfiles_dirs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='dirs',
            field=models.JSONField(default=[0], verbose_name='ID директорий, где есть ссылка'),
        ),
    ]
