# Generated by Django 4.0.2 on 2022-04-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_window', '0004_links_rename_user_data_userdata'),
        ('main_window', '0005_user_data_delete_userdata'),
    ]

    operations = [
    ]
